const SITE = {
  salesName: "Alya Honda",
  dealer: "Honda Bintang Sragen",
  phoneDisplay: "0821 3848 6851",
  phoneWa: "6282138486851",
  heroTitle: "Wujudkan Mobil Impianmu.",
  heroText: "Konsultasikan kebutuhan mobil Honda Anda dengan Alya. Cek pilihan model, referensi harga, promo, simulasi kredit, trade-in dan test drive.",
  promoTitle: "PROMO HONDA & PRICE LIST",
  promoText: "Tanyakan promo, stok, warna, paket kredit dan harga OTR Sragen terbaru langsung melalui WhatsApp Alya.",
  location: { address: "Jl. Kebayan 1, Jetak, Kec. Sidoharjo, Kabupaten Sragen, Jawa Tengah 57213", hours: "Senin–Jumat 08.00–17.00 • Sabtu–Minggu/Hari Libur 08.00–15.00" },
  priceNote: "Harga Jateng di bawah adalah referensi resmi Honda untuk area yang tercantum pada tabel (antara lain Solo, Klaten, Kudus, Pati, Salatiga, Cilacap, Magelang, Purwokerto, Semarang, Jepara, Pekalongan dan Tegal). Harga OTR Sragen, promo, warna, stok dan program pembiayaan wajib dikonfirmasi ke dealer.",
  cars: [
    {id:"brio",name:"Honda Brio",category:"CITY CAR",price:"Rp177.000.000*",priceNumber:177000000,priceType:"OTR referensi Jawa Tengah",image:"assets/cars/brio.svg",tagline:"City car ringkas, irit dan praktis untuk harian.",description:"Honda Brio memakai mesin 1.2L i-VTEC 90 PS dengan pilihan transmisi M/T dan CVT.",features:["1.2L i-VTEC 90 PS","110 Nm","M/T & CVT","Digital A/C","7” Display Audio","ABS + EBD"],variants:["Satya S M/T","Satya S CVT","Satya E M/T","Satya E CVT","RS CVT"],colors:["Taffeta White","Rallye Red","Meteoroid Gray Metallic","Ignite Red Metallic","Electric Lime Metallic"],source:"https://www.honda-indonesia.com/Brio"},
    {id:"wrv",name:"Honda WR-V",category:"SUV",price:"Rp282.600.000*",priceNumber:282600000,priceType:"OTR referensi Jawa Tengah",image:"assets/cars/wrv.svg",tagline:"Compact SUV sporty untuk mobilitas kota dan perjalanan.",description:"New Honda WR-V hadir dengan pembaruan desain, konektivitas dan kenyamanan.",features:["1.5L i-VTEC","Compact SUV","Display Audio 10.25” pada varian tertentu","Wireless Smartphone Connection","USB-C","Honda Sensing pada varian tertentu"],variants:["E M/T","E CVT","RS","RS with Honda Sensing"],colors:["Taffeta White","Ignite Red Metallic","Meteoroid Gray Metallic","Crystal Black Pearl"],source:"https://www.honda-indonesia.com/"},
    {id:"brv",name:"Honda BR-V N7X",category:"FAMILY SUV",price:"Rp338.400.000*",priceNumber:338400000,priceType:"OTR referensi Jawa Tengah",image:"assets/cars/brv.svg",tagline:"SUV 7-seater untuk keluarga dan perjalanan jauh.",description:"BR-V N7X memadukan kapasitas 7 penumpang, mesin 1.5L i-VTEC dan karakter SUV.",features:["7-Seater","1.5L i-VTEC","121 PS","145 Nm","Honda Sensing pada varian tertentu","Kabin fleksibel"],variants:["N7X E CVT","N7X Prestige CVT","N7X Prestige with Honda Sensing"],colors:["Sand Khaki Pearl","Platinum White Pearl","Meteoroid Gray Metallic","Crystal Black Pearl"],source:"https://www.honda-indonesia.com/"},
    {id:"cityhatch",name:"Honda City Hatchback RS",category:"HATCHBACK",price:"Rp385.400.000*",priceNumber:385400000,priceType:"OTR referensi Jawa Tengah",image:"assets/cars/cityhatch.svg",tagline:"Hatchback sporty dengan karakter RS.",description:"City Hatchback RS menawarkan gaya sporty, kabin praktis dan mesin 1.5L i-VTEC.",features:["1.5L i-VTEC","121 PS","CVT","Honda Sensing","RS Styling","Smartphone Connection"],variants:["CVT","CVT Two Tone"],colors:["Ignite Red Metallic","Platinum White Pearl","Meteoroid Gray Metallic","Brilliant Sporty Blue Metallic"],source:"https://www.honda-indonesia.com/"},
    {id:"city",name:"New Honda City",category:"SEDAN",price:"Rp402.000.000*",priceNumber:402000000,priceType:"Harga resmi Honda — OTR Jakarta; OTR Jateng konfirmasi",image:"assets/cars/city.svg",tagline:"Sedan elegan dengan Honda SENSING.",description:"New Honda City mengusung mesin 1.5L i-VTEC 121 PS dan fitur Honda SENSING.",features:["1.5L DOHC i-VTEC","121 PS","145 Nm","CVT","Honda SENSING","Smart Key"],variants:["New Honda City CVT"],colors:["Platinum White Pearl","Meteoroid Gray Metallic","Brilliant Sporty Blue Metallic","Ignite Red Metallic"],source:"https://www.honda-indonesia.com/city"},
    {id:"hrv",name:"Honda HR-V",category:"SUV",price:"Rp397.300.000*",priceNumber:397300000,priceType:"OTR referensi Jawa Tengah",image:"assets/cars/hrv.svg",tagline:"SUV modern dengan pilihan teknologi e:HEV.",description:"Honda HR-V menawarkan desain modern, kenyamanan dan pilihan varian bensin serta hybrid sesuai lineup.",features:["Compact SUV","Pilihan bensin & e:HEV","Honda Sensing","Konektivitas modern","RS e:HEV pada varian tertentu","Interior premium"],variants:["S CVT","E CVT","SE CVT","TURBO RS","RS e:HEV*"],colors:["Platinum White Pearl","Ignite Red Metallic","Meteoroid Gray Metallic","Crystal Black Pearl"],source:"https://www.honda-indonesia.com/"},
    {id:"civic",name:"Honda Civic RS e:HEV",category:"SPORT SEDAN",price:"Rp629.300.000*",priceNumber:629300000,priceType:"OTR referensi Jawa Tengah",image:"assets/cars/civic.svg",tagline:"Civic hybrid dengan karakter sporty dan teknologi modern.",description:"New Honda Civic RS e:HEV menggabungkan mesin hybrid, Honda CONNECT dan Honda SENSING.",features:["2.0L e:HEV","203 PS total system","315 Nm motor","E-CVT","Honda CONNECT","BOSE 12 Speakers"],variants:["Civic RS e:HEV"],colors:["Platinum White Pearl","Meteoroid Gray Metallic","Crystal Black Pearl","Ignite Red Metallic"],source:"https://www.honda-indonesia.com/civic"},
    {id:"crv",name:"New Honda CR-V",category:"PREMIUM SUV",price:"Rp760.900.000*",priceNumber:760900000,priceType:"OTR referensi Jawa Tengah",image:"assets/cars/crv.svg",tagline:"SUV premium dengan pilihan hybrid.",description:"New Honda CR-V hadir dengan kenyamanan premium dan pilihan teknologi e:HEV.",features:["1.5L Turbo / 2.0L e:HEV","Honda Sensing","Kabin lapang","Honda CONNECT","Varian RS e:HEV","Multi-view camera pada varian tertentu"],variants:["1.5L Turbo","2.0L RS e:HEV"],colors:["Platinum White Pearl","Meteoroid Gray Metallic","Crystal Black Pearl","Ignite Red Metallic"],source:"https://www.honda-indonesia.com/"},
    {id:"stepwgn",name:"Honda STEP WGN e:HEV",category:"MPV / HYBRID",price:"Rp637.800.000*",priceNumber:637800000,priceType:"Harga resmi Honda — OTR Jakarta; OTR Jateng konfirmasi",image:"assets/cars/stepwgn.svg",tagline:"MPV keluarga dengan teknologi e:HEV dan kabin fleksibel.",description:"STEP WGN e:HEV menggabungkan ruang kabin luas, konfigurasi fleksibel dan teknologi hybrid Honda.",features:["e:HEV Hybrid","7-Seater","Kabin fleksibel","Honda Sensing","Honda CONNECT","Comfortable family MPV"],variants:["STEP WGN e:HEV"],colors:["Platinum White Pearl","Meteoroid Gray Metallic","Crystal Black Pearl"],source:"https://www.honda-indonesia.com/"},
    {id:"accord",name:"All New Honda Accord",category:"SEDAN PREMIUM",price:"Rp972.200.000*",priceNumber:972200000,priceType:"OTR referensi Jawa Tengah",image:"assets/cars/accord.svg",tagline:"Sedan flagship dengan teknologi hybrid e:HEV.",description:"All New Honda Accord RS e:HEV menghadirkan mesin hybrid, Honda CONNECT dan Honda SENSING.",features:["2.0L e:HEV","207 PS electric motor","335 Nm","E-CVT","12.3” Display Audio","BOSE 12 Speakers"],variants:["2.0L RS e:HEV"],colors:["Platinum White Pearl","Meteoroid Gray Metallic","Crystal Black Pearl","Canyon River Blue Metallic"],source:"https://www.honda-indonesia.com/accord"},
    {id:"civictyper",name:"Honda Civic Type R",category:"PERFORMANCE",price:"Rp1.447.100.000*",priceNumber:1447100000,priceType:"OTR referensi Jawa Tengah",image:"assets/cars/civictyper.svg",tagline:"Performance hatchback dengan transmisi manual 6-percepatan.",description:"Civic Type R merupakan model performa tinggi Honda dengan karakter pengendaraan yang fokus pada pengalaman sporty.",features:["2.0L VTEC Turbo","6-speed Manual","Performance chassis","Honda SENSING","Sporty aerodynamics","High-performance brakes"],variants:["Civic Type R 6 M/T"],colors:["Championship White","Rallye Red","Crystal Black Pearl"],source:"https://www.honda-indonesia.com/"},
    {id:"en1",name:"Honda e:N1",category:"ELECTRIC",price:"Hubungi Alya",priceNumber:0,priceType:"Harga resmi Honda: hubungi dealer; OTR Jateng konfirmasi",image:"assets/cars/en1.svg",tagline:"SUV listrik baterai Honda dengan 204 PS dan 310 Nm.",description:"Honda e:N1 adalah BEV Honda untuk Indonesia dengan motor listrik 204 PS dan baterai 68,8 kWh.",features:["BEV","204 PS","310 Nm","Battery 68.8 kWh","Range hingga 500 km NEDC","Honda Sensing"],variants:["e:N1"],colors:["Platinum White Pearl","Urban Gray Pearl","Crystal Black Pearl"],source:"https://www.honda-indonesia.com/en1"},
    {id:"prelude",name:"Honda Prelude",category:"SPORT HYBRID",price:"Rp974.900.000*",priceNumber:974900000,priceType:"Harga resmi Honda — OTR Jakarta; OTR Jateng konfirmasi",image:"assets/cars/prelude.svg",tagline:"Sport hybrid coupe dua pintu dengan e:HEV.",description:"Honda Prelude resmi hadir di Indonesia pada 2026 sebagai sport hybrid dengan sistem e:HEV dan S+ Shift.",features:["2.0L e:HEV","203 PS total system","315 Nm motor","E-CVT","S+ Shift","Honda SENSING"],variants:["Prelude e:HEV"],colors:["Platinum White Pearl","Ignite Red Metallic","Crystal Black Pearl"],source:"https://www.honda-indonesia.com/prelude"},
    {id:"superone",name:"Honda Super-ONE",category:"ELECTRIC / CONCEPT",price:"Rp438.000.000*",priceNumber:438000000,priceType:"Harga mulai Honda — OTR Jakarta; konfirmasi ketersediaan Jateng",image:"assets/cars/superone.svg",tagline:"Model elektrifikasi Honda dalam lineup terbaru.",description:"Honda menampilkan Super-ONE pada lineup harga terbaru Honda Indonesia. Ketersediaan unit dan OTR wilayah perlu dikonfirmasi dealer.",features:["Elektrifikasi","Desain kompak","Teknologi Honda","Konsultasi unit","Harga dapat berubah","Konfirmasi dealer"],variants:["Super-ONE"],colors:["Tanya Alya"],source:"https://www.honda-indonesia.com/promotions"}
  ],
  legacy: [
    {id:"crz",name:"Honda CR-Z",category:"MODEL LEGACY",price:"Bukan unit baru",image:"assets/cars/crz.svg",description:"CR-Z merupakan model Honda yang sudah tidak dipasarkan sebagai mobil baru. Cocok ditampilkan sebagai referensi model legacy / unit bekas.",source:"https://www.honda-indonesia.com/honda-service"},
    {id:"jazz",name:"Honda Jazz",category:"MODEL LEGACY",price:"Bukan unit baru",image:"assets/cars/jazz.svg",description:"Honda Jazz merupakan model lama yang tidak tercantum sebagai unit baru pada lineup Honda Indonesia saat ini.",source:"https://www.honda-indonesia.com/honda-service"},
    {id:"freed",name:"Honda Freed",category:"MODEL LEGACY",price:"Bukan unit baru",image:"assets/cars/freed.svg",description:"Honda Freed merupakan model lama. Untuk unit bekas, silakan konsultasikan ketersediaan dengan Alya.",source:"https://www.honda-indonesia.com/honda-service"},
    {id:"mobilio",name:"Honda Mobilio",category:"MODEL LEGACY",price:"Bukan unit baru",image:"assets/cars/mobilio.svg",description:"Honda Mobilio merupakan model lama dan bukan bagian dari lineup mobil baru saat ini.",source:"https://www.honda-indonesia.com/honda-service"}
  ]
};
